# Generated by Django 4.1.3 on 2022-11-18 23:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_reactiontype'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReactionEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_experienced', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('recipetype', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.reactiontype')),
            ],
        ),
    ]
