# Generated by Django 4.0.2 on 2022-11-10 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_diaryentry_user_diaryentry_recipe_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='selected',
            new_name='favorited',
        ),
        migrations.AddField(
            model_name='recipe',
            name='planner',
            field=models.BooleanField(default=False),
        ),
    ]
