# Generated by Django 4.0.2 on 2022-11-19 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_recipetype_reactionentry_reactiontype'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DiaryEntr',
            new_name='DiaryEntry',
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='category',
            field=models.ManyToManyField(to='core.Category'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='genres',
            field=models.ManyToManyField(to='core.Genre'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(to='core.Ingredient'),
        ),
    ]
