# Generated by Django 4.0.2 on 2022-11-16 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_rename_time_recipe_total_time_recipe_cook_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='name_concat',
            field=models.CharField(default='DINO-NUGGIES', max_length=200),
            preserve_default=False,
        ),
    ]
