# Generated by Django 4.0.2 on 2022-11-16 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_rename_ingredients_recipe_ingredient'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='genre',
            new_name='genres',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='ingredient',
            new_name='ingredients',
        ),
    ]
