# Generated by Django 4.0.2 on 2022-11-16 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_rename_genre_recipe_genres_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='name_concat',
        ),
        migrations.AddField(
            model_name='recipe',
            name='uuid',
            field=models.UUIDField(default=0),
            preserve_default=False,
        ),
    ]
